### ISSUE TITLE
Проект для репозитория

### ISSUE THREAD

**Issue by Kkhludneva** [citec-spbu/Spatial-Data-ETL#1]
Создать проект для репозитория, чтобы отражать прогресс по задачам. Нужна помощь администратора организации.

**Comment by sevryukov** [comment]
@Kkhludneva Создал проект, выдал Вам права администратора в этом проекте. Проверьте, пожалуйста, всё ли ок.

**Comment by Kkhludneva** [comment]
@sevryukov Да, всё в порядке. Спасибо!
