### ISSUE TITLE
Загрузка данных - Загрузить данные с osmtoday.com 

### ISSUE THREAD

**Issue by Kkhludneva** [citec-spbu/Spatial-Data-ETL#10]
- Загрузить файл с данными по Санкт-Петербургу (.pbf)
- Загрузить .pbf в Postgres
- Отфильтровать объекты типа amenity
- Визуализировать данные в qgis.

В качестве справочного материала использовать записи лекций из #8

**Comment by nikita03565** [comment]
Коллеги @Kkhludneva @Guywash-Ka, как идет работа над задачей? Есть ли трудности, про которые хочется что-то спросить? Если удобнее и приятнее что-то обсудить не в формате комментариев к ишью, то можно в телеграме

**Comment by Guywash-Ka** [comment]
Нет, все окей. В процессе

**Comment by nikita03565** [comment]
Коллеги, продолжаю наблюдать за вами. Появился вопрос по [ПРу](https://github.com/citec-spbu/Spatial-Data-ETL/pull/16/files): как был получен файл osm_spb_pdf.pdf на всего 600кб из pbf файла на 1гб для всего северо-западного округа? Какими утилитами и конкретными командами? Пример преобразования/фильтрации было бы очень полезно указать в md файле @Guywash-Ka 

Еще будет нужно продумать работу скрипта для автоматизированной загрузки данных. Может быть пока без реализации, а в виде описания алгоритма на естесственном языке. И аналогично для способа загрузки через overpass api (osmnx). И затем выбрать какой способ больше подходит, например, организовав сравнение по различным критериям из разряда "достоинства, недостатки, ограничения", и приступить уже к реализации. Но это уже больше возможные планы на дальнейшие задачи.

@Kkhludneva предлагаю эти планы и текущие проблемы/вопросы обсудить на созвоне вместе с Сергеем Юрьевичем, как договорились в [ишью](https://github.com/citec-spbu/Spatial-Data-ETL/issues/8#issuecomment-2007634856)

**Comment by Guywash-Ka** [comment]
Насчет размера пдф файла - там просто обрезанный кусок карты в виде картинки, сомневаюсь, что он должен весить больше, просто для быстрого ознакомления. Создавал в qbis через экспорт->экспортировать в пдф. Замечу, что там информация только по ресторанам

**Comment by nikita03565** [comment]
Ах, это я получается неправильно прочитал, перепутал p**B**f и p**D**f.. Подумал, что вы сделали какую-то выборку с данными из большого p**B**f файла, как [тут](https://osm2pgsql.org/examples/road-length/), и приложили ее как пример. Но суть комментария остается без изменений -- указывайте используемые команды в файлах с ресерчем, пригодится на будущее для сравнения подходов и, возможно, написания реализации (и для понимания, что именно и как было сделано).

Рекомендую посмотреть другие примеры https://osm2pgsql.org/examples/ , чтобы понять как перекладывать в постгрес только нужные данные (отфильтрованные по области и/или значениям тегов).
@Guywash-Ka
