### ISSUE TITLE
Исследовать инструменты для работы с pbf файлами

### ISSUE THREAD

**Issue by Kkhludneva** [citec-spbu/Spatial-Data-ETL#17]
Посмотреть, как можно:
- Отобрать нужные объекты
- Отфильтровать по географической области в виде полигона или bbox'а
- Прочитать pbf средствами питона 

Изучить возможности osm2pgsql

**Comment by Kkhludneva** [comment]
@Guywash-Ka @TigranNice перенесите, пожалуйста, ваши наработки по задаче в комментарии под это issue

**Comment by TigranNice** [comment]
https://download.geofabrik.de/
качаем данные отсюда один раз
![image](https://github.com/citec-spbu/Spatial-Data-ETL/assets/75087976/9c159aa2-1807-4379-aaaa-263df64ea06c)
Есть проблема с взятием России, она находится в двух частях света: Азия и Европа. Надо рассмотреть объединение 2 регионов.

https://pyrosm.readthedocs.io/en/latest/index.html
используется для работы с pbf в пайтон

**Comment by TigranNice** [comment]
Есть вариант использования Osmosis, чтобы в дальнейшем использовать для обновления бд.

**Comment by TigranNice** [comment]
> @TigranNice
> 
> > Есть проблема с взятием России, она находится в двух частях света: Азия и Европа. Надо рассмотреть объединение 2 регионов.
> 
> Можете пояснить в чем проблема взятия России? Ссылка одна и та же https://download.geofabrik.de/russia.html , если пытаться попасть в Россию со страниц Европы или Азии. Россия там везде полная (не разделена на европейскую и азиатскую части)
> 
> Посмотреть как делать операции объединения все равно будет полезно и может пригодиться.
> 
> Pyrosm хорошая находка

Невнимательно изучил скачивание файлов! Спасибо, что подправили!

**Comment by TigranNice** [comment]
https://docs.osmcode.org/pyosmium/latest/intro.html

Pyosmium, думаю это то что нам надо
