### ISSUE TITLE
Выгрузка данных с OSM 

### ISSUE THREAD

**Issue by Kkhludneva** [citec-spbu/Spatial-Data-ETL#2]
Ознакомиться со структурой хранения данных в OSM, библиотеками для работы с геоданными в python. Получить данные с ресурса.
(см https://habr.com/ru/articles/579838/ )

**Comment by igordanilov692002** [comment]
ссылка на colab с проведенным исследованием: https://colab.research.google.com/drive/1nlEW77FS2Fs_Oy3QzWvMC9wO8D8zjdvu?usp=sharing

**Comment by potomushozhenya** [comment]
Добавили в research.
https://github.com/citec-spbu/Spatial-Data-ETL/commit/81e1cb8fa1305e584d7c75dd2362bba34a23a5e1
