### ISSUE TITLE
Изучить методы обновления данных - временные дельты

### ISSUE THREAD

**Issue by Kkhludneva** [citec-spbu/Spatial-Data-ETL#20]
Изучить методы актуализации данных OSM, например:
		https://wiki.openstreetmap.org/wiki/RU:Osmupdate

Учитываем, что работать предстоит с большими объемами данных (РФ/Евразия/планета)
	
Отразить все рассуждения в комментариях под issue.

**Comment by TigranNice** [comment]
Порядок действий такой: используем OSM DIFF, далее Osmosis в связке с osm2pgsql обновляем данные в бд

**Comment by TigranNice** [comment]
Скорее всего не подходит, тк последняя репликация для россии была в 2020 году, а бд обновляется каждый день

**Comment by nikita03565** [comment]
@TigranNice 
Можете показать какой-то пруф, что для России нет данных свежее 2020 года? Скриншот, ссылка, описание куда сходить, чтобы посмотреть

[Говорят](https://wiki.openstreetmap.org/wiki/Planet.osm/diffs), `osmupdate`, который вы же предложили к рассмотрению, умеет брать нужные дифф файлы
> Alternatively, the [osmupdate](https://wiki.openstreetmap.org/wiki/Osmupdate) can be used to create cumulated diff files (.osc, .osc.gz, .o5c, .o5c.gz). The program will download all necessary diffs between a given timestamp and now. Depending on this period of time, minutely, hourly and daily diffs will be downloaded and processed. It is faster than Osmosis and a bit easier to handle but it lacks a lot of functionality Osmosis provides, for example, osmupdate cannot update databases or write full history diffs (there will be only the newest version of each object in the output file).

Не изучали подробнее как это у него получается и насколько подходит?

На геофабрике кстати тоже есть osc.gz файлы, но они обновляются только раз в день. Если жестко обязательно уметь обновлять чаще, то тогда конечно не подходит.

**Comment by TigranNice** [comment]
![IMG_1475](https://github.com/citec-spbu/Spatial-Data-ETL/assets/75087976/5b705310-7c33-4a19-981a-d85f56aef3fa)
![IMG_1476](https://github.com/citec-spbu/Spatial-Data-ETL/assets/75087976/bb055e8e-190b-4f1b-93aa-6f0c36c0ebaa)

Я зашёл в базу данных OSM и напрямую посмотрел. В Репликациях видно, что последняя была сделана в 2020! 
А на другом скрине видно что сама база данных по России обновлена на 2024.04.09

**Comment by nikita03565** [comment]
@TigranNice 
Там ведь, если зайти внутрь, то можно увидеть, что в папке с минутными апдейтами все обновляется как по часам каждую минуту. К тому же для каждого субрегиона: 
https://download.openstreetmap.fr/replication/russia/
https://download.openstreetmap.fr/replication/russia/southern_federal_district/krasnodar_krai/

Похоже в 2020 году были загружены начальные данные, а минутные оттуда получается брать можно (но скорее всего не стоит раз дневных и часовых изменений нет и покрытие не полное "provides minutely diffs (.osc.gz) of around 20 countries, check link for availibility")

**Comment by TigranNice** [comment]
Можно брать все апдейты которые были за день
![image](https://github.com/citec-spbu/Spatial-Data-ETL/assets/75087976/eed51a96-9e68-416b-83e9-fe015b408fa5)
 Т е поставить время, например 0:00 для обновления. Программа будет брать все файлы, которые есть в базе и применять их к нашей бд

**Comment by TigranNice** [comment]
![image](https://github.com/citec-spbu/Spatial-Data-ETL/assets/75087976/25ffd22a-d18d-432d-a108-24b5f81c643e)
А лучше изучил сайт https://wiki.openstreetmap.org/wiki/Planet.osm/diffs
Нашёл что можно брать ежедневные изменения
![image](https://github.com/citec-spbu/Spatial-Data-ETL/assets/75087976/aee23db3-0d6a-4f4a-986a-6694bb181bfc)

**Comment by TigranNice** [comment]
https://docs.osmcode.org/pyosmium/latest/ref_replication.html

нашёл обновление репликаций в pyosmium

**Comment by nikita03565** [comment]
@TigranNice можно вас попросить опубликовать до начала разработки краткое, но при этом достаточно понятное описание того, как вы планируете делать обновление данных? Какими инструментами и какая стратегия будет использоваться

Например:
- качаем самостоятельно минутные диффы (как и откуда),
- последовательно их применяем от старых к новым,
- распаковываем, парсим xml,
- в xml будет указано, что нужно добавить/удалить/изменить, делаем соотвествующие запросы к базе

(специально привел пример очень неудачной стратегии)

Если составление такого плана выходит за рамки конкретно этой задачи, то создать новую задачу нет проблем, главное, чтобы этот план был где-то зафиксирован. Относится ко всем задачам, где нужно что-то изучить и продумать как какой-то компонент будет работать.

Мудрая мысль для вас и всех ваших коллег:
Вносить изменения в документы (какие угодно, [требования](https://en.wikipedia.org/wiki/Software_requirements_specification) или планы-описания будущих работ по реализации) написанные на человеческом языке (русский, английский и тд) во много раз проще, чем вносить изменения в уже написанный и работающий код.

Дополнительная выгода в состовлении подобных описаний: в конце семестра, когда вам нужно будет писать отчет по проекту или составлять презентацию для его защиты, достаточно будет только скопировать это описание вместо того, чтобы напрягать память или пытаться понять по коду как все работает и почему работает именно так.

@Kkhludneva @sevryukov

**Comment by sevryukov** [comment]
> Мудрая мысль для вас и всех ваших коллег:
Вносить изменения в документы (какие угодно, [требования](https://en.wikipedia.org/wiki/Software_requirements_specification) или планы-описания будущих работ по реализации) написанные на человеческом языке (русский, английский и тд) во много раз проще, чем вносить изменения в уже написанный и работающий код.

Совершенно верно! Есть несколько од про это (они уже не такие свежие по дате издания, но не потерявшие актуальность):
Коротко и просто: https://okiseleva.blogspot.com/2018/03/blog-post_59.html
Обстоятельно: https://habr.com/ru/articles/332724/

**Comment by potomushozhenya** [comment]
#42
