### ISSUE TITLE
Изучить методы для извлечения данных применимые к нашей задаче

### ISSUE THREAD

**Issue by Kkhludneva** [citec-spbu/Spatial-Data-ETL#22]
Нас интересует первичная загрузка: работать предстоит с большими объемами данных (РФ/Евразия/планета). Определить каким способом осуществлять первичную загрузку: из pbf файла/API/скачать и развернуть дамп?

**Comment by potomushozhenya** [comment]
API очевидно использовать невыгодно, как с точки зрения разработки данного процесса, таки с точки затраченного времени.
Скачать данные можно только в форматах XML, PBF, BZ2.
Считаю, что можно использовать два варианта наполнения БД информацией. Первый: Загрузка из локально находящегося файла. Второй: загрузка нужного файла скриптом

Использованные ссылки:
https://wiki.openstreetmap.org/wiki/Setting_up_a_local_copy_of_the_OpenStreetMap_database,_kept_up_to_date_with_minutely_diffs
https://wikitech.wikimedia.org/wiki/Openstreetmap_Databases
https://wiki.openstreetmap.org/w/images/1/10/ERD_of_OSM_DB.svg
https://planet.openstreetmap.org/
