### ISSUE TITLE
Разделение данных

### ISSUE THREAD

**Issue by TigranNice** [citec-spbu/Spatial-Data-ETL#23]
Рассмотреть H3 структуру. Сравнить с разделением в OSM

![image](https://github.com/citec-spbu/Spatial-Data-ETL/assets/75087976/b7d7ecaa-0f38-48e6-a730-2bab5ab1d909)
![image](https://github.com/citec-spbu/Spatial-Data-ETL/assets/75087976/5985e65e-7cbf-4512-b220-bfcb0daacda0)

**Comment by potomushozhenya** [comment]
Я считаю, что стоит остановиться на разбиении, как у разработчиков. Потому что у нас не только ситуация, когда данные находятся рядом друг с другом в географическом смысле. Также само внедрение H3 займет приличный пласт времени. Ввиду всего вышеперечисленного считаю, что использование H3 нецелесообразно.
Ссылки для ознакомления:
https://habr.com/ru/articles/715622/
https://habr.com/ru/articles/714326/
