### ISSUE TITLE
Исследование структуры загружаемых pbf файлов.

### ISSUE THREAD

**Issue by potomushozhenya** [citec-spbu/Spatial-Data-ETL#24]
Анализ структуры pbf с оф. сайта и geofabrik.

**Comment by potomushozhenya** [comment]
https://download.openstreetmap.fr/extracts/russia.osm.pbf
https://download.geofabrik.de/russia-latest.osm.pbf

**Comment by nikita03565** [comment]
@Guywash-Ka @potomushozhenya @TigranNice 
[https://download.openstreetmap.fr](https://download.openstreetmap.fr/extracts/russia.osm.pbf) это не официальный сайт. единственный официальный это https://planet.openstreetmap.org
Все остальное это data extracts из planet osm.

С главной страницы геофабрика:
> Welcome to Geofabrik's free download server. This server has **data extracts** from the [OpenStreetMap project](http://www.openstreetmap.org/) which are normally updated every day.

Со страницы  [вики](https://wiki.openstreetmap.org/wiki/Planet.osm/diffs), раздел **Regionally limited diffs**:
> http://download.openstreetmap.fr/replication/ provides minutely diffs (.osc.gz) of around 20 countries, check link for availibility (You can contact [User:Jocelyn](https://wiki.openstreetmap.org/wiki/User:Jocelyn) for more information)

Использовать data extracts это не плохо само по себе, но нужно учитывать ограничения на поддерживаемые регионы, как у французского сайта.

Разницы в структуре файлов полученных с разных ресурсов кстати быть не должно. В данных еще может быть, например, файлы сгенерированы в немного разное время, но структура должна быть везде одинаковой.

**Comment by potomushozhenya** [comment]
Для первой ссылки:
![capture_20240419003529834](https://github.com/citec-spbu/Spatial-Data-ETL/assets/123594106/31d707c2-ce05-44d7-82aa-a020a81117c6)

**Comment by potomushozhenya** [comment]
Для второй
![capture_20240419012859550](https://github.com/citec-spbu/Spatial-Data-ETL/assets/123594106/9ce5145a-303e-4e5d-b19d-bc7c438bf87e)

**Comment by sevryukov** [comment]
@Kkhludneva что стало результатом задачи и где с ним можно ознакомиться? Уточните, пожалуйста.

**Comment by Kkhludneva** [comment]
Нужно было посмотреть, какой будет структура таблиц при загрузке pbf России (скачанных с 2х разных ресурсов) в postgis. Хотели убедиться, что структура таблиц будет одинаковой вне зависимости от источника. 
Скриншоты со структурой таблиц  представлены в комментариях выше - она действительно одинаковая.
@sevryukov

**Comment by sevryukov** [comment]
@Kkhludneva у меня диссонанс: наименование задачи и её скромное описание не совпадают с тем, что Вы пишите.
Либо надо изменить наименование и описание задачи, либо решить задуманное изначально.

Я полагал, что изучение структуры pbf приведёт вас к изучению [официальной документации](https://wiki.openstreetmap.org/wiki/RU:PBF_Format#:~:text=%D0%A4%D0%BE%D1%80%D0%BC%D0%B0%D1%82%20PBF%20%D0%B1%D1%8B%D0%BB%20%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%BD%20%D0%B4%D0%BB%D1%8F,%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%BE%D0%B2%20OSM%20%D0%B2%20%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D0%BE%D0%B9%20%D0%BA%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8.), к примеру.
