### ISSUE TITLE
Сервер + postgres. Поднятие, развертывание, пробные скрипты

### ISSUE THREAD

**Issue by Guywash-Ka** [citec-spbu/Spatial-Data-ETL#27]
# Подняли сервер, настроили БД и повертели питона

Подняли линукс сервер, где будет работать наша система (по крайней мере ближайшее время для удобной работы)
Установили и настроили postgreSQL. Написали небольшой скрипт на питоне, который автоматически загружает pbf файл в БД. Пока что значения названия файлов и БД написаны в самом скрипте, но это позже будет отдельно обсуждаться и изменяться, в зависимости от вариантов исполнения

Настройкой сервера занимался @potomushozhenya - вопросы по серверу к нему.

ПР со скриптом: https://github.com/citec-spbu/Spatial-Data-ETL/pull/26

**Comment by nikita03565** [comment]
Инструкции по настройке сервера тоже стоит куда-то сохранить в репозитории (не в ишью даже, а в репозитории кажется будет лучше), чтобы максимально полная информация о проекте сохранилась и может быть пригодится кому-то в будущем. Может даже вам самим же, чтобы окружение поднять на локальных машинах

**Comment by potomushozhenya** [comment]
@nikita03565 Все настройки севера будут учтены в скриптах, остальные не потребуются для работы.
