### ISSUE TITLE
MVP - Скрипт для установки PostGis

### ISSUE THREAD

**Issue by Kkhludneva** [citec-spbu/Spatial-Data-ETL#28]
Написать скрипт для установки PostGis на ту машину, на которой будет запущено наше решение (операционная система - linux)

**Comment by potomushozhenya** [comment]
https://github.com/citec-spbu/Spatial-Data-ETL/pull/32

**Comment by sevryukov** [comment]
@Kkhludneva @potomushozhenya хорошо, что берётесь за автоматизацию настройки окружения.

В https://github.com/citec-spbu/Spatial-Data-ETL/pull/32 @nikita03565 правильно замечает, что Python - не первое средство автоматизации для настройки окружения и (добавлю) в отрасли уже есть некоторые стандарты типа использования контейнеров или средств типа [Ansible](https://github.com/ansible/ansible).

Т.к. времени немного, то при наличии других задач можно взять технический долг и зафиксировать задачу миграции с написанного скрипта на отраслевые средства IaaS. Пока же сосредоточиться на других задачах.

**Comment by potomushozhenya** [comment]
Первый рабочий mvp в ветке https://github.com/citec-spbu/Spatial-Data-ETL/tree/mvp-v1
