### ISSUE TITLE
Скачивание и обновление дельт

### ISSUE THREAD

**Issue by TigranNice** [citec-spbu/Spatial-Data-ETL#33]

**Comment by TigranNice** [comment]
![image](https://github.com/citec-spbu/Spatial-Data-ETL/assets/75087976/c12d2f79-a566-466a-adc1-4e98ed678f9c)

**Comment by nikita03565** [comment]
цель в использовании дельт это упрощение/ускорение процесса обновления. если каждый раз будем перекачивать новые огромные файлы, то это будет долго

[геофабрик](https://download.geofabrik.de/south-america/argentina.html) дает скачать osc файлы (с разницей за день)
> [.osc.gz files](https://download.geofabrik.de/south-america/argentina-updates) that contain all changes in this region, suitable e.g. for Osmosis updates

и дает скачать старые версии pbf файлов
![image](https://github.com/citec-spbu/Spatial-Data-ETL/assets/33401112/ed8597ca-c1d3-4763-bd6a-ff037e0b4454)

это можно использовать для различных экспериментов

**Comment by nikita03565** [comment]
@sevryukov Сергей Юрьевич, может быть явно объявим, что поддержка обновлений чаще чем раз в день не обязательна для упрощения логики работы?
Дневные апдейты взять легко на геофабрике, а с часовыми и минутными есть трудности. При этом частота более раза в день кажется избыточной. По ощущениям (серьезных сравнений не проводил) существенных изменений в данных за такое небольшое время не накопится

У меня была мысль, что получится использовать инструмент [osmupdate](https://wiki.openstreetmap.org/wiki/Osmupdate), но в вики говорят:
> Project status not clear, according to [discussion on mailing list in February 2021](https://lists.openstreetmap.org/pipermail/dev/2021-February/031072.html).

Если его перестают поддерживать, то полагаться на него и не стоит

**Comment by nikita03565** [comment]
Так еще скажу: если за несколько часов заставить работать osmupdate не получится, то лучше не тратить еще больше времени и выбрать откатиться к более простой в плане логики и реализации идее. Согласны или подход плох?

**Comment by sevryukov** [comment]
> Сергей Юрьевич, может быть явно объявим, что поддержка обновлений чаще чем раз в день не обязательна для упрощения логики работы?

Коллеги, полностью согласен, что начинать надо с самого простого и усложнять только при необходимости.

@nikita03565 @TigranNice

**Comment by nikita03565** [comment]
@TigranNice давайте создадим ПР и обсужения кода будем вести там
если код там еще не завершен, то можно пометить ПР как драфт

**Comment by nikita03565** [comment]
> можно пометить ПР как драфт

![image](https://github.com/citec-spbu/Spatial-Data-ETL/assets/33401112/2e2019ea-c093-4b3c-8e35-fe779f641bdf)

@TigranNice
