### ISSUE TITLE
Применение дельт

### ISSUE THREAD

**Issue by Kkhludneva** [citec-spbu/Spatial-Data-ETL#38]
В нашей БД данные будут разделены по регионам:

          central-fed-district
          central-fed-district
          crimean-fed-district
          far-eastern-fed-district
          kaliningrad
          north-caucasus-fed-district
          northwestern-fed-district
          siberian-fed-district
          south-fed-district
          ural-fed-district
          volga-fed-district 

Для каждого региона храним таблицы с геом примитивами (line, point, polygon, roads)
Дельты тоже будут скачиваться для каждого региона по отдельности. 

Необходимо придумать, как применять дельты к вышеописанной структуре бд.
Названия таблиц согласовать с #39

**Comment by TigranNice** [comment]
https://ircama.github.io/osm-carto-tutorials/updating-data/#implementing-the-update-procedure:~:text=on%20the%20service.-,Implementing%20the%20update%20procedure,-Once%20configuration.txt

**Comment by TigranNice** [comment]
![image](https://github.com/citec-spbu/Spatial-Data-ETL/assets/75087976/341436cd-43e2-4704-842d-5ee06229f8c6)

**Comment by potomushozhenya** [comment]
#42
