### ISSUE TITLE
Проектирование ETL сценария

### ISSUE THREAD

**Issue by Kkhludneva** [citec-spbu/Spatial-Data-ETL#5]
• Продумать логику: сбор (в промежуточное хранилище/просто в дата фрейм?) -> преобразование(зависит от структуры бд на выходе) -> выгрузка в БД
• Механика: как связать части процесса? 

В конце спринта (+- 13.03 - 15.03) презентовать команде идею

**Comment by potomushozhenya** [comment]
Будем использовать Apache Airflow. Его будем разворачивать в Docker. Docker и БД будут на той машине, на которой будет устанавливаться наше решение.
