### ISSUE TITLE
Подключить ещё одного члена команды

### ISSUE THREAD

**Issue by Kkhludneva** [citec-spbu/Spatial-Data-ETL#7]
Один из членов команды, Копылов Игорь, не отображается в assignees. Письмо с приглашением подключиться к репозиторию ему не приходило.

Почта: igor.danilov692002@mail.ru
Профиль на github: igordanilov692002

**Comment by sevryukov** [comment]
@Kkhludneva доступ предоставлен.
@AngW1SH проверь, пожалуйста, почему студента не было в списке?
