### ISSUE TITLE
Загрузка данных - Загрузить данные с помощью библиотеки OSMNX

### ISSUE THREAD

**Issue by Kkhludneva** [citec-spbu/Spatial-Data-ETL#9]
В качестве территории взять часть Санкт-Петербурга. Подобрать область так, чтобы были загружены объекты с разными геометрическими примитивами: nodes, lines, relations.

Подготовить ноутбук, отразить в нём
- процесс загрузки
- визуализацию (пока можно с помощью folium)
- вывод собранных данных

**Comment by nikita03565** [comment]
Не уверен, что писать в закрытую ишью это хорошая идея, но прокомментировать некоторые моменты хочется.

Посмотрел ноутбук. Показалось, что может сложиться неверное понимание значений тегов и их взаимосвязи друг с другом. То, что в них много пропущенных значений, не может являться достаточным основанием для выбрасывания их из рассмотрения, хотя мысль о необходимости фильтрации тегов совершенно верная. Рекомендую поисследовать [вики](https://wiki.openstreetmap.org/wiki/Key:amenity), чтобы понять, что теги значат и с какими комбинациями обычно используются. Например у ресторана может быть указано кухня: итальянская, а для банка тег с кухней не имеет значения и его соответственно там не будет, а будет что-то свое. 

Рекомендации по организации и форме:
1. Должно быть осмысленное оформление [пулл реквестов](https://github.com/citec-spbu/Spatial-Data-ETL/pull/11). Название, краткое описание, ссылка на задачу
2. По возможности указывайте своих коллег в качестве ревьюеров в пулл реквестах (и по возможности ревьюйте друг друга). Очень полезный навык, извлекайте как можно больше из работы в команде над учебными проектами.

@Kkhludneva @TigranNice 
@sevryukov
